Repository apache/apisix-dashboard, pull requests merged in 2020-12, with the labels that each got.

#893 test: add route with priority (E2E)
  api/test/e2e/route_with_priority_test.go
Labels: backend

#874 test: add route with invalid remote_addr (E2E)
  api/test/e2e/route_remote_addr_test.go
Labels: backend, discuss

#880 test: add consumer test ( E2E )
  api/test/e2e/consumer_test.go
Labels: backend

#947 fix: snowflake remove network dependency
  api/go.sum
  api/internal/utils/utils.go
  api/internal/utils/utils_test.go
Labels: backend, bug

#897 test: e2e test chash upstream with key (remote_addr)
  api/test/e2e/upstream_test.go
Labels: backend

#953 test: fix the problem that consumer test cases cause CI failure (E2E)
  api/test/e2e/consumer_test.go
Labels: CI

#951 feat: add etcd basic auth support
  api/conf/conf.go
  api/conf/conf.yaml
  api/go.sum
  api/internal/core/storage/etcd.go
  api/internal/handler/consumer/consumer_test.go
  api/internal/handler/route/route_test.go
  api/internal/handler/service/service_test.go
  api/internal/handler/ssl/ssl_test.go
  api/internal/handler/upstream/upstream_test.go
  api/main.go
  api/test/shell/cli_test.sh
Labels: enhancement

#981 feat(CI): supoort markdown links checker
  .github/workflows/markdown-link-checker.yml
Labels: CI, enhancement

#959 release: new version 2.1.1
  CHANGELOG.md
  README.md
  docs/FAQ.md
  docs/deploy-with-docker.md
  docs/deploy.md
  docs/develop.md
  web/package.json
Labels: backend, frontend

#900 feat: add version info into manager-api
  api/VERSION
  api/build.sh
  api/main.go
  api/test/shell/cli_test.sh
Labels: enhancement

#868 fix: delete POST method in /apisix/admin/consumer
  api/internal/handler/consumer/consumer.go
  api/internal/handler/consumer/consumer_test.go
  api/test/e2e/consumer_test.go
Labels: backend

#859 feat: add a unit test for consumer and remove implicit init
  api/conf/conf.go
  api/filter/logging_test.go
  api/internal/core/store/store.go
  api/internal/core/store/store_mock.go
  api/internal/handler/consumer/consumer.go
  api/internal/handler/consumer/consumer_test.go
  api/log/zap.go
Labels: backend

#1031 fix(plugin): set disable but useless
  web/config/proxy.ts
  web/src/components/Plugin/PluginPage.tsx
Labels: plugin

#978 Refactor online debug fe
  web/package.json
  web/src/pages/Consumer/List.tsx
  web/src/pages/Route/List.tsx
  web/src/pages/Route/components/DebugViews/AuthenticationView.tsx
  web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
  web/src/pages/Route/components/DebugViews/DebugParamsView.tsx
  web/src/pages/Route/components/DebugViews/index.less
  web/src/pages/Route/components/DebugViews/index.ts
  web/src/pages/Route/constants.ts
  web/src/pages/Route/locales/en-US.ts
  web/src/pages/Route/locales/zh-CN.ts
  web/src/pages/Route/service.ts
  web/src/pages/Route/typing.d.ts
  web/src/pages/Upstream/List.tsx
  web/yarn.lock
Labels: pending

#999 feat: add route group
  web/src/locales/en-US/component.ts
  web/src/locales/zh-CN/component.ts
  web/src/pages/Route/Create.tsx
  web/src/pages/Route/List.tsx
  web/src/pages/Route/components/Step1/LabelsDrawer.tsx
  web/src/pages/Route/components/Step1/MetaView.tsx
  web/src/pages/Route/constants.ts
  web/src/pages/Route/service.ts
  web/src/pages/Route/transform.ts
  web/src/pages/Route/typing.d.ts
Labels: frontend

#1105 test: add frontend e2e test (smoke test for settings page)
  web/cypress/integration/settings/settings-smoketest.spec.js
Labels: pending
