Repository apache/apisix-dashboard, pull requests merged in 2020-11, with the labels that each got.

#689 chore: refactor error log for `manager api`
  .github/workflows/cli_test.yml
  Dockerfile
  api/Dockerfile
  api/conf/conf.go
  api/conf/conf.json
  api/conf/conf.yaml
  api/conf/conf_preview.json
  api/filter/logging.go
  api/filter/recover.go
  api/go.mod
  api/go.sum
  api/internal/core/store/query.go
  api/internal/core/store/store.go
  api/internal/core/store/storehub.go
  api/internal/core/store/validate.go
  api/internal/handler/route/route.go
  api/log/log.go
  api/log/zap.go
  api/logs/placeholder.txt
  api/main.go
  api/test/docker/manager-api-conf.yaml
  api/test/shell/cli_test.sh
Labels: backend

#871 docs: currently considered experimental.
  README.md
Labels: documentation

#884 test: add route with valid remote_address (E2E)
  api/test/e2e/route_with_valid_remote_addr_test.go
Labels: backend

#888 test: add route with uri or uris ( E2E )
  api/test/e2e/route_with_uri_uris_test.go
Labels: backend

#892 test: add e2e test cases for route with log plugin
  api/test/docker/apisix_config.yaml
  api/test/docker/docker-compose.yaml
  api/test/e2e/route_with_log_plugin_test.go
  api/test/e2e/route_with_valid_remote_addr_test.go
Labels: backend

#895 test: add route with vars ( E2E )
  api/test/e2e/base.go
  api/test/e2e/route_with_vars_test.go
Labels: backend, testcase

#903 test: add e2e test cases for route with trace plugin
  api/test/docker/apisix_config.yaml
  api/test/docker/docker-compose.yaml
  api/test/e2e/route_with_trace_plugin_test.go
Labels: backend, testcase

#894 test: add e2e test cases for route with metric plugin
  api/test/e2e/route_with_metric_plugin_test.go
Labels: backend
