Repository apache/apisix-dashboard, pull requests merged in 2021-01, with the labels that each got.

#1202 fix(be): change bodyParams to string to accept any content-type
  api/internal/handler/route_online_debug/route_online_debug.go
  api/test/e2e/route_online_debug_test.go
Labels: backend

#1225 feat: Improve consumer for i18n (#1212)(backport to v2.3)
  web/src/locales/zh-CN/menu.ts
  web/src/pages/Consumer/locales/en-US.ts
  web/src/pages/Consumer/locales/zh-CN.ts
Labels: backport

#1228 fix: sync the preload packages in schema-sync.lua (#1221)(backport to v2.3)
  api/build-tools/schema-sync.lua
Labels: backport

#1283 fix: omit taobao mirror
  web/cypress/integration/plugin/schema-smocktest.spec.js
  web/src/app.tsx
  web/src/components/ActionBar/ActionBar.tsx
  web/src/components/HeaderDropdown/index.tsx
  web/src/components/NoticeIcon/NoticeList.tsx
  web/src/components/NoticeIcon/index.tsx
  web/src/components/Plugin/PluginDetail.tsx
  web/src/components/Plugin/PluginPage.tsx
  web/src/components/Plugin/service.ts
  web/src/components/Plugin/typing.d.ts
  web/src/components/PluginOrchestration/components/SidebarItem.tsx
  web/src/components/PluginOrchestration/customConfig.tsx
  web/src/components/PluginOrchestration/index.tsx
  web/src/components/PluginOrchestration/service.ts
  web/src/components/PluginOrchestration/typing.d.ts
  web/src/components/RightContent/AvatarDropdown.tsx
  web/src/components/RightContent/index.tsx
  web/src/helpers.tsx
  web/src/pages/404.tsx
  web/src/pages/Consumer/List.tsx
  web/src/pages/Consumer/components/Preview.tsx
  web/src/pages/Consumer/components/Step1.tsx
  web/src/pages/Consumer/typing.d.ts
  web/src/pages/Plugin/List.tsx
  web/src/pages/Plugin/service.ts
  web/src/pages/Plugin/typing.d.ts
  web/src/pages/Route/List.tsx
  web/src/pages/Route/components/CreateStep4/CreateStep4.tsx
  web/src/pages/Route/components/DebugViews/DebugDrawView.tsx
  web/src/pages/Route/components/ResultView/ResultView.tsx
  web/src/pages/Route/components/Step1/LabelsDrawer.tsx
  web/src/pages/Route/components/Step3/index.tsx
  web/src/pages/Route/transform.ts
  web/src/pages/Route/typing.d.ts
  web/src/pages/SSL/List.tsx
  web/src/pages/SSL/components/CertificateForm/index.tsx
  web/src/pages/SSL/components/CertificateUploader/index.tsx
  web/src/pages/SSL/components/Step1/index.tsx
  web/src/pages/SSL/components/Step2/index.tsx
  web/src/pages/ServerInfo/List.tsx
  web/src/pages/Service/List.tsx
  web/src/pages/Service/components/Preview.tsx
  web/src/pages/Service/typing.d.ts
  web/src/pages/Setting/typingd.d.ts
  web/src/pages/Upstream/List.tsx
  web/src/pages/Upstream/components/Step1.tsx
  web/src/pages/Upstream/typing.d.ts
  web/src/pages/User/Login.tsx
  web/src/pages/User/Logout.tsx
  web/src/pages/User/components/LoginMethodExample.tsx
  web/src/pages/User/components/LoginMethodPassword.tsx
  web/src/pages/User/typing.d.ts
  web/src/services/API.d.ts
  web/src/typings.d.ts
  web/yarn.lock
Labels: frontend

#1289 fix: Support string type for the script field in Route
  api/internal/handler/route/route.go
  api/internal/handler/route/route_test.go
  api/internal/utils/utils.go
  api/internal/utils/utils_test.go
  api/test/e2e/base.go
  api/test/e2e/route_with_script_luacode_test.go
Labels: backend, help wanted

#1284 fix: Client-side URL redirect
  web/cypress/integration/route/create-edit-delete-route.spec.js
  web/src/components/Plugin/PluginPage.tsx
  web/src/components/Plugin/data.tsx
  web/src/components/Plugin/typing.d.ts
  web/src/pages/Route/components/Step3/index.tsx
  web/src/pages/Setting/Setting.tsx
  web/src/typings.d.ts
Labels: frontend

#1054 fix: ssl config support set labels
  api/internal/handler/ssl/ssl.go
  api/internal/handler/ssl/ssl_test.go
  api/test/e2e/ssl_test.go
Labels: wait for update

#1333 chore: add stop subcommand
  Makefile
  api/cmd/managerapi.go
  api/internal/conf/conf.go
  api/internal/utils/pid.go
  api/test/shell/cli_test.sh
  docs/deploy.md
Labels: documentation

#1240 feat(fe): import and export routes
  docs/IMPORT_OPENAPI_USER_GUIDE.md
  web/cypress/fixtures/export-route-dataset.json
  web/cypress/fixtures/import-error.txt
  web/cypress/fixtures/selector.json
  web/cypress/integration/route/import_export_route.spec.js
  web/cypress/plugins/index.js
  web/cypress/support/commands.js
  web/package.json
  web/src/pages/Route/List.tsx
  web/src/pages/Route/constants.ts
  web/src/pages/Route/locales/en-US.ts
  web/src/pages/Route/locales/zh-CN.ts
  web/src/pages/Route/service.ts
  web/yarn.lock
Labels: frontend
