Repository apache/apisix-dashboard, pull requests merged in 2021-11, with the labels that each got.

#2198 test: migrate consumer e2e
  api/go.mod
  api/go.sum
  api/test/e2e/consumer_test.go
  api/test/e2enew/consumer/consumer_suite_test.go
  api/test/e2enew/consumer/consumer_test.go
  api/test/e2enew/consumer/consumer_with_labels_test.go
  api/test/e2enew/consumer/consumer_with_plugin_key_auth_test.go
  api/test/e2enew/go.mod
  api/test/e2enew/go.sum
Labels: testcase, backend

#2199 fix: backend e2e testcase typo
  api/test/e2enew/consumer/consumer_test.go
Labels: bug, testcase

#2208 fix: login page description link
  web/src/pages/User/components/LoginMethodPassword.tsx
Labels: bug, frontend

#2225 ci: clean up the E2E test environment
  api/test/docker/docker-compose.yaml
  api/test/docker/upstream.conf
Labels: backend, CI

#2202 test: migrate global rule e2e
  api/test/e2e/global_rule_test.go
  api/test/e2enew/global_rule/global_rule_suite_test.go
  api/test/e2enew/global_rule/global_rule_test.go
Labels: testcase, backend

#2228 fix: migrate testcase CI crash
  api/test/e2enew/migrate/migrate_test.go
Labels: bug, backend, CI

#2226 fix: plugin_configs should store with etcd prefix
  api/internal/core/store/storehub.go
Labels: bug, backend
